export const CONSTANTS = {
  VEHICLE_TYPES: {
    CAR: 'CAR',
    CNG: 'CNG',
  },
  RIDE_STATUS: {
    REQUESTED: 'REQUESTED',
    MATCHED: 'MATCHED',
    STARTED: 'STARTED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
  },
  POOL_STATUS: {
    ACTIVE: 'ACTIVE',
    FULL: 'FULL',
    STARTED: 'STARTED',
    COMPLETED: 'COMPLETED',
  },
  MIN_PASSENGERS: 2,
  MAX_PASSENGERS_CAR: 3,
  PICKUP_RANGE_KM: 2,
};